import Link from 'next/link';

export default function Home() {
  return <main className="landing">
    <nav className="nav"><Link href="/" className="brand"><img src="/pulse-mark.svg" alt="" /> <span>PULSE PROTOCOL</span></Link><div className="navLinks"><a href="#platform">Platform</a><a href="#features">Features</a><a href="#about">About</a></div><a className="button ghost" href="https://app.pulseprotocol.co/trade">Open terminal</a></nav>
    <section className="hero"><div className="heroCopy"><p className="eyebrow">THE TRADING TERMINAL FOR THE NEXT CYCLE</p><h1>Trade with a clearer pulse.</h1><p className="intro">Pulse Protocol brings multi-exchange execution, SmartTrades, bots and market intelligence into one focused workspace — built for traders who want control without the noise.</p><div className="actions"><a className="button primary" href="https://app.pulseprotocol.co/trade">Open Pulse Terminal ↗</a><a className="button ghost" href="#features">Explore the platform</a></div></div><div className="terminal"><div className="terminalTop"><span>BTCUSDT · 4H</span><span className="live">● LIVE</span></div><div className="chart"><svg viewBox="0 0 600 220" preserveAspectRatio="none"><polyline points="0,184 44,170 75,178 110,142 145,156 180,124 220,137 255,95 291,112 330,74 365,87 400,52 438,70 470,42 510,58 548,25 600,10" fill="none" stroke="#5de1d0" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round"/><circle cx="548" cy="25" r="6" fill="#5aa7ff"/></svg></div><div className="quote"><div><small>Market pulse</small><strong>Risk-aware</strong></div><div className="right"><small>BTC</small><strong className="positive">+4.8%</strong></div></div></div></section>
    <section id="platform" className="section"><p className="eyebrow">ONE WORKSPACE. EVERY DECISION.</p><h2>Built around your process.</h2><p className="lead">A practical command centre for discretionary traders and systematic strategies, with the context you need before you click.</p><div id="features" className="cards"><article><b>01</b><h3>Multi-exchange terminal</h3><p>Connect the venues you use and keep execution in one consistent interface.</p></article><article><b>02</b><h3>SmartTrades & bots</h3><p>Plan entries, take-profits, stop-losses and automation with precision.</p></article><article><b>03</b><h3>Market intelligence</h3><p>Read trend, momentum, relative strength and breakout context in plain language.</p></article></div></section>
    <section id="about" className="cta"><div><p className="eyebrow">PULSE PROTOCOL</p><h2>Build your process. Keep your edge.</h2><p className="lead">The platform is read-only until you choose to trade. Your strategy stays yours.</p></div><a className="button primary" href="https://app.pulseprotocol.co/trade">Enter the terminal ↗</a></section>
    <footer><span>© 2026 Pulse Protocol</span><span><a href="mailto:stephan@pulseprotocol.co">stephan@pulseprotocol.co</a> · <a href="https://app.pulseprotocol.co">app.pulseprotocol.co</a></span></footer>
  </main>;
}
